version: '3'
services:
  ldap:
    image: osixia/openldap:1.1.7
  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2023-08-31T15-31-16Z
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio-client
      - MINIO_VOLUMES=/mnt/data
    volumes:
      - minio:/mnt/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command:
      [
        "minio",
        "server",
        "--console-address",
        ":9090"
      ]
  mysql:
    container_name: mysql
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=ninetofiver
      - MYSQL_DATABASE=ninetofiver
      - MYSQL_USER=ninetofiver
      - MYSQL_PASSWORD=ninetofiver
    ports:
      - "3307:3306"
    # expose:
    #   - "3306"
    volumes:
      - mysql:/var/lib/mysql
      - './docker-compose/initdb.d:/docker-entrypoint-initdb.d'
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--wait_timeout=28800',
        '--max_allowed_packet=128M'
      ]

  925r:
    build:
      context: 925r
      dockerfile: Dockerfile
    # command: bash -c "python manage.py migrate && python -Wa manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py migrate && pipenv run gunicorn --pid /run/gunicorn/ninetofiver.pid --bind 0.0.0.0:9101 --env ENVIRONMENT=production --timeout 60 --workers=5 --worker-class sync --worker-connections 1000 --access-logfile /var/log/gunicorn/access-ninetofiver.log --error-logfile /var/log/gunicorn/error-ninetofiver.log --capture-output ninetofiver.wsgi"
    container_name: 925r
    hostname: 925r
    expose:
      - "9101"
    ports:
      - "8888:9101"
    volumes:
      - ./925r:/code
    depends_on:
      - ldap
      - mysql
      - minio

  yayata:
    container_name: yayata
    hostname: yayata
    command: bash -c "ls"
    build:
      context: yayata
      dockerfile: tests/docker/yayata.Dockerfile
    # working_dir: /code/yayata
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./yayata/src:/code/src
      - ./config.json:/code/src/static/cfg/config.json
    depends_on:
      - 925r

volumes:
  minio:
  mysql:
