---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        version: "5.7"
    spec:
      containers:
        - name: mysql
          image: "mysql:5.7"
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              value: yayata
            - name: MYSQL_USER
              value: yayata
            - name: MYSQL_PASSWORD
              value: yayata
            - name: MYSQL_ROOT_PASSWORD
              value: random-password
          args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --wait_timeout=28800
            - --max_allowed_packet=128M
          livenessProbe:
            exec:
              # @see https://github.com/kubernetes/kubernetes/issues/40846#issuecomment-415014405
              # Sidenote: mysqladmin ping does not need a user and password to succeed
              command: ["bash", "-c", "MYSQL_PWD=${MYSQL_PASSWORD}", "mysqladmin", "--host", "127.0.0.1", "--user", "${MYSQL_USER}", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              # @see https://github.com/kubernetes/kubernetes/issues/40846#issuecomment-415014405
              # Check if we can execute actual queries
              command: ["bash", "-c", "MYSQL_PWD=${MYSQL_PASSWORD}", "mysql", "--host", "127.0.0.1", "--user", "${MYSQL_USER}", "--execute", "SELECT 1"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
#      restartPolicy: Always
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql
